#!/usr/bin/env python
from selenium.webdriver.common.by import By

class FunnelLocs(object):

    COUNTRYDDL = (By.CLASS_NAME, "numberchooser-country")
    STATEDDL = (By.CLASS_NAME, "numberchooser-state")
    AREACODEDDL = (By.CLASS_NAME, "numberchooser-city")
    FNAME_INPT = (By.CLASS_NAME, "firstname")
    LNAME_INPT = (By.CLASS_NAME, "lastname")
    COMPANY_NAME_INPT = (By.CLASS_NAME, "companyName")
    ADDRESS_1_INPT = (By.CLASS_NAME, "address1")
    ADDRESS_2_INPT = (By.CLASS_NAME, "address2")
    BILL_COUNTRY_DDL = (By.CLASS_NAME, "country")
    BILL_CITY_INPT = (By.CLASS_NAME, "city")
    BILL_STATE_DDL = (By.CLASS_NAME, "state")
    ZIPCODE_INPT = (By.CLASS_NAME, "zipcode")
    PHONE_INPT = (By.CLASS_NAME, "phone")
    CARD_HOLDER_INPT = (By.CLASS_NAME, "creditcardname")
    CARD_TYPE_DDL = (By.CLASS_NAME, "creditcardtype")
    CC_NUM_INPT = (By.CLASS_NAME, "creditcardnumber")
    MONTH_EXP_DDL = (By.CLASS_NAME, "creditcard-exp-month")
    YEAR_EXP_DDL = (By.CLASS_NAME, "creditcard-exp-year")
    CVV_INPT = (By.CLASS_NAME, "cvv")
    AGREEMENT_INPT = (By.CLASS_NAME, "customer-agreement")
    PLACE_ORDER = (By.CLASS_NAME, "agreement")
    ESSENTIAL_MONTH_RDIO = (By.ID, "essential-month")
    ESSENTIAL_ANNUAL_RDIO = (By.ID, "essential-year")
    ESSENTIAL_NEXT_BTN = (By.CLASS_NAME, "btnessential")
    VALUE_MONTH_RDIO = (By.ID, "value-month")
    VALUE_ANNAUL_RDIO = (By.ID, "value-year")
    VALUE_NEXT_BTN = (By.CLASS_NAME, "btnvalue")
    PRO_MONTH_RDIO = (By.ID, "professional-month")
    PRO_MONTH_ANNUAL_RDIO = (By.ID, "professional-year")
    PRO_NEXT_BTN = (By.CLASS_NAME, "btnprofessional")
    MONTHY_FEE_LBL = (By.ID, "paidsignup_periodicFee")
    ACTIVATE_FEE_LBL = (By.ID, "paidsignup_activationFee")
    S4_PAGES_INC_LBL = (By.ID, "paidsignup_FreePages")
